version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    env_file: .env 
    volumes:
      - mongodb_data:/data/db
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - mongo
volumes:
  mongodb_data:

